### ISSUE TITLE
Cargo

### ISSUE THREAD

**Issue by titmouse84** [Zalexanninev15/Arch-EIP#5]
Had an error of "ModuleNotFoundError: No module named 'qdarktheme" solved with 'paru -S python-pyqtdarktheme' Is there any way you could add rust packages installed by "cargo install" to the query. I love this program by the way. It's been extremely helpful and I'm surprised it's not more popular. I've never uploaded anything to the AUR bit if you have any suggestions on how that could be done (ie make it installable) I would be honored to maintain it.

**Comment by Zalexanninev15** [comment]
Hi. Thank you for your interest in the project, I thought no one needs it but me. Regarding your problem, the package is called "pyqtdarktheme" ([PyPI](https://pypi.org/project/pyqtdarktheme/)). About cargo, it is quite possible to implement. The other problem is that I don't plan to move to Linux again because of third party projects for Windows and because I'm waiting for the stable KDE 6 and Nobara Linux using it. But I will definitely take your wish into account during development. If you want, you can test the 1.3 branch: https://github.com/Zalexanninev15/Arch-EIP/tree/version-1.3

**Comment by Zalexanninev15** [comment]
> Had an error of "ModuleNotFoundError: No module named 'qdarktheme" solved with 'paru -S python-pyqtdarktheme' Is there any way you could add rust packages installed by "cargo install" to the query. I love this program by the way. It's been extremely helpful and I'm surprised it's not more popular. I've never uploaded anything to the AUR bit if you have any suggestions on how that could be done (ie make it installable) I would be honored to maintain it.

I started developing a new version. We plan to support Cargo and Fedora (dnf), because I have long since moved to the latter. The new version will be released only as a console implementation. I had to abandon the GUI due to display problems in the GNOME 4x desktop environment.

**Comment by Zalexanninev15** [comment]
New version: https://github.com/Zalexanninev15/Arch-EIP/tree/version-1.3

**Comment by Zalexanninev15** [comment]
> Had an error of "ModuleNotFoundError: No module named 'qdarktheme" solved with 'paru -S python-pyqtdarktheme' Is there any way you could add rust packages installed by "cargo install" to the query. I love this program by the way. It's been extremely helpful and I'm surprised it's not more popular. I've never uploaded anything to the AUR bit if you have any suggestions on how that could be done (ie make it installable) I would be honored to maintain it.

A version with Cargo support has just been released in the repository.
